import crypto from "node:crypto";

import {
  AlertSeverity,
  AlertSource,
  AlertStatus,
  DeployProvider,
  DeployStatus,
  ErrorLevel,
  ErrorProvider,
  IncidentSeverity,
  IncidentStatus,
  LogLevel,
  TimelineEventType,
} from "@prisma/client";
import { prisma } from "./prisma";

function pick<T>(values: T[]): T {
  return values[Math.floor(Math.random() * values.length)] as T;
}

function randomDateWithinHours(hoursBack: number): Date {
  const now = Date.now();
  const span = hoursBack * 60 * 60 * 1000;
  return new Date(now - Math.floor(Math.random() * span));
}

function randomSha(): string {
  return crypto.randomBytes(20).toString("hex");
}

async function nextIncidentKey() {
  const latest = await prisma.incident.findFirst({
    orderBy: { createdAt: "desc" },
    select: { incidentKey: true },
  });

  const latestNumber = latest?.incidentKey ? Number.parseInt(latest.incidentKey.split("-")[1] ?? "0", 10) : 0;
  return `INC-${String((Number.isFinite(latestNumber) ? latestNumber : 0) + 1).padStart(6, "0")}`;
}

async function main() {
  const services = await prisma.service.findMany({
    select: {
      id: true,
      name: true,
      teamId: true,
      environments: {
        select: {
          id: true,
          name: true,
        },
      },
    },
  });

  const users = await prisma.user.findMany({
    select: {
      id: true,
      name: true,
    },
  });

  if (services.length === 0 || users.length === 0) {
    throw new Error("Services and users are required before sync-mock-events can run.");
  }

  const ingestCounts = {
    incidents: 0,
    deploys: 0,
    errors: 0,
    logs: 0,
    alerts: 0,
  };

  for (let i = 0; i < 12; i += 1) {
    const service = pick(services);
    const environment = pick(service.environments);
    const key = await nextIncidentKey();
    const startedAt = randomDateWithinHours(72);
    const severity = pick([IncidentSeverity.SEV1, IncidentSeverity.SEV2, IncidentSeverity.SEV3, IncidentSeverity.SEV4]);
    const status = pick([IncidentStatus.OPEN, IncidentStatus.INVESTIGATING, IncidentStatus.MITIGATED]);

    const incident = await prisma.incident.create({
      data: {
        teamId: service.teamId,
        serviceId: service.id,
        incidentKey: key,
        title: `${service.name} ${pick(["latency regression", "error spike", "throughput drop", "dependency timeout"])} `,
        severity,
        status,
        startedAt,
        detectedAt: startedAt,
        acknowledgedAt: status === IncidentStatus.OPEN ? null : new Date(startedAt.getTime() + 9 * 60_000),
        summary: `Synthetic incident generated by sync script for realism testing.`,
        impact: `Potential customer impact detected in ${environment.name}.`,
        createdByUserId: pick(users).id,
        commanderUserId: pick(users).id,
      },
    });

    ingestCounts.incidents += 1;

    await prisma.incidentTimelineEvent.createMany({
      data: [
        {
          incidentId: incident.id,
          type: TimelineEventType.CREATED,
          message: `${incident.incidentKey} auto-generated by sync script`,
          createdByUserId: incident.createdByUserId,
        },
        {
          incidentId: incident.id,
          type: TimelineEventType.NOTE,
          message: `Initial triage complete, collecting correlated deploy/error signals.`,
          createdByUserId: incident.commanderUserId,
        },
      ],
    });

    await prisma.deployEvent.create({
      data: {
        serviceId: service.id,
        environmentId: environment.id,
        provider: pick([DeployProvider.GITHUB, DeployProvider.GITLAB, DeployProvider.CIRCLECI, DeployProvider.MANUAL]),
        externalId: `sync-deploy-${Date.now()}-${i}`,
        commitSha: randomSha(),
        commitMessage: `Synthetic sync deploy for ${service.name}`,
        branch: pick(["main", "release", "hotfix"]),
        author: pick(["sam", "morgan", "jules", "dana"]),
        startedAt: randomDateWithinHours(36),
        finishedAt: randomDateWithinHours(35),
        status: pick([DeployStatus.SUCCEEDED, DeployStatus.FAILED, DeployStatus.ROLLED_BACK]),
        url: `https://ci.example.dev/sync/${i}`,
      },
    });

    ingestCounts.deploys += 1;

    await prisma.errorEvent.create({
      data: {
        serviceId: service.id,
        environmentId: environment.id,
        provider: pick([ErrorProvider.SENTRY, ErrorProvider.DATADOG, ErrorProvider.ROLLBAR, ErrorProvider.MANUAL]),
        fingerprint: `sync-fingerprint-${Date.now()}-${i}`,
        title: `${service.name} synthetic error burst`,
        level: pick([ErrorLevel.ERROR, ErrorLevel.WARNING, ErrorLevel.FATAL]),
        firstSeenAt: randomDateWithinHours(24),
        lastSeenAt: randomDateWithinHours(4),
        occurrences: 20 + Math.floor(Math.random() * 150),
        url: `https://errors.example.dev/sync/${i}`,
        rawJson: { sync: true, incidentId: incident.id },
      },
    });

    ingestCounts.errors += 1;

    const logs = Array.from({ length: 120 }).map((_, logIndex) => ({
      serviceId: service.id,
      environmentId: environment.id,
      level: pick([LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR, LogLevel.DEBUG]),
      message: `sync-log-${i}-${logIndex}: ${pick(["request path", "retry", "cache write", "queue ack", "job timeout"])}`,
      timestamp: randomDateWithinHours(12),
      traceId: crypto.randomBytes(8).toString("hex"),
      spanId: crypto.randomBytes(6).toString("hex"),
      source: pick(["api", "worker", "scheduler"]),
      rawJson: { sync: true, index: logIndex },
    }));

    const logInsert = await prisma.logEvent.createMany({ data: logs });
    ingestCounts.logs += logInsert.count;

    await prisma.alertEvent.create({
      data: {
        incidentId: incident.id,
        serviceId: service.id,
        source: pick([AlertSource.DATADOG, AlertSource.CLOUDWATCH, AlertSource.PROMETHEUS, AlertSource.MANUAL]),
        alertKey: `SYNC-ALERT-${Date.now()}-${i}`,
        title: `${service.name} synthetic threshold breach`,
        severity: pick([AlertSeverity.CRITICAL, AlertSeverity.HIGH, AlertSeverity.MEDIUM]),
        triggeredAt: randomDateWithinHours(8),
        status: pick([AlertStatus.TRIGGERED, AlertStatus.ACKED]),
        payloadJson: { sync: true, incidentKey: incident.incidentKey },
      },
    });

    ingestCounts.alerts += 1;
  }

  console.info("sync-mock-events complete");
  console.info(JSON.stringify(ingestCounts, null, 2));
}

main()
  .catch((error) => {
    console.error("sync-mock-events failed", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
